Notes
osunyorg/admin pull request #1714
Opened 2024-03-18 08:39 UTC by arnaudlevy

2024-04-15 19:18 UTC, alexisben commented
J'ai testé, en contrib c'est pas trop utilisable. Sans passer en mode code, je n'arrive pas à sauter une ligne ou quitter la note, ni à supprimer une note vide.

2024-04-15 19:30 UTC, alexisben commented
Ok, et j'ai eu vraiment du mal à comprendre comment l'utiliser, j'avais envie d'appliquer la note sur un mot ou un ensemble de mots.

2024-04-15 20:32 UTC, arnaudlevy commented
@alexisben j'ai pas compris. 

Pourquoi tu veux sauter une ligne dans une note ? Pourquoi tu cliques pas après la note tout simplement ? Ou peut-être que tu as créé une note à la fin du texte ? J'ai pas testé ça.

Pour supprimer une note vide quel est le pb ?

2024-04-18 06:38 UTC, SebouChu requested changes
En plus des retours, les summernote sans note n'ont plus de toolbar, par exemple dans le formulaire d'une formation

2024-04-18 06:38 UTC, SebouChu commented on app/assets/javascripts/application/plugins/summernote.js
> +            ['b', 'strong', 'i', 'em', 'sup', 'a', 'ul', 'ol', 'li'],
peut-être autoriser la nouvelle balise `<note>` dans le cas d'un copier-coller ?

2024-04-18 06:38 UTC, SebouChu commented on app/helpers/admin/application_helper.rb
> +    # We need an index for the whole page
je comprends pas ce commentaire

2024-04-18 06:38 UTC, SebouChu commented on app/services/osuny/notes.rb
> +        @text_with_notes << build_note(part)
`@text_with_notes +=` plutôt que `@text_with_notes <<` non ?

J'ai l'impression que c'est un tableau avec `<<` alors que c'est une string

2024-04-18 06:38 UTC, SebouChu commented on app/assets/javascripts/application/plugins/summernote.js
> +    note: function (context) {
je propose de le nommer `noteButton` pour être parlant, puis ça matche avec [leur doc](https://summernote.org/deep-dive/#custom-button)

2024-04-18 06:38 UTC, SebouChu commented on app/views/admin/communication/blocks/edit.html.erb
> +            note: window.summernoteManager.note
je propose de le nommer `noteButton` pour être parlant, puis ça matche avec [leur doc](https://summernote.org/deep-dive/#custom-button)

2024-04-18 16:32 UTC, arnaudlevy commented
Il faut réparer les summernotes hors vue

2024-04-19 08:04 UTC, SebouChu approved these changes

2024-04-19 08:05 UTC, merged