Refonte des options de bloc
osunyorg/admin pull request #1850
Opened 2024-04-29 06:56 UTC by arnaudlevy

https://developers.osuny.org/docs/theme/architecture/options/

2024-05-02 14:13 UTC, pabois commented
Ca me semble ok mais je veux bien un double check de @SebouChu

2024-05-06 15:33 UTC, SebouChu requested changes

2024-05-06 15:33 UTC, SebouChu commented on app/helpers/admin/blocks_helper.rb
> +  def block_options(block)
`block_options_static` pour être iso avec `block_component_static` ?

2024-05-06 15:33 UTC, SebouChu commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
```
template.option_summary       = template.show_summary
```

2024-05-06 15:33 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/agenda/_edit.html.erb
> +    <%= block_component_edit block, :option_summary, label: t('admin.summary.label')%>
l'espace avant la fermeture du tag `%>`

2024-05-06 15:33 UTC, SebouChu commented on app/models/communication/block/template/page.rb
>    has_component :show_main_description, :boolean
et donc lui pas en deprecated, tu me confirmes?

2024-05-07 18:19 UTC, arnaudlevy commented on app/helpers/admin/blocks_helper.rb
> +  def block_options(block)
ok !

2024-05-07 18:21 UTC, arnaudlevy commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
ok aussi !

2024-05-07 18:21 UTC, arnaudlevy commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
Bien vu :)

2024-05-07 18:22 UTC, arnaudlevy commented on app/models/communication/block/template/page.rb
>    has_component :show_main_description, :boolean
oui c'est pas une option qu'on peut passer aux pages dans la config.yaml, c'est spécial pour la main page

2024-05-13 08:42 UTC, SebouChu approved these changes

2024-05-13 09:09 UTC, pabois approved these changes

2024-07-03 14:21 UTC, alexisben requested changes

2024-07-03 14:21 UTC, alexisben commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
```suggestion
      template.option_main_summary       = template.show_main_description
      template.option_summaries          = template.show_descriptions
```

2024-07-03 14:24 UTC, alexisben requested changes

2024-07-03 14:24 UTC, alexisben commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
```suggestion
      template.option_images       = template.show_images
```

2024-07-03 14:31 UTC, arnaudlevy commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
j'avais laissé les options globales en dehors, tu préfères dedans ?

2024-07-03 16:24 UTC, arnaudlevy commented
@alexisben je comprends pas bien tes suggestions.
J'ai compris que tu voulais le `show_main_description` du bloc pages dans les options.
Mais le reste je vois pas. Images au pluriel, c'est pas cohérent avec les autres options.

2024-07-03 16:26 UTC, arnaudlevy commented on app/models/communication/block/template/agenda.rb
> +  has_component :option_status,       :boolean, default: false
Donc @alexisben je masque : 
- [ ] option_dates
- [ ] option_image
- [ ] option_subtitle
Dans les formulaires d'édition ?

2024-07-03 16:26 UTC, arnaudlevy commented on app/models/communication/block/template/location.rb
> +  has_component :option_summary,      :boolean, default: true
Là je masque les 2, on n'avait aucune option

2024-07-03 16:28 UTC, Olivia206 commented on app/models/communication/block/template/agenda.rb
> +  has_component :option_status,       :boolean, default: false
c'est ça ! on les intègrera après la première passe

2024-07-03 16:29 UTC, arnaudlevy commented on app/models/communication/block/template/organization.rb
> +  has_component :option_summary,      :boolean, default: false
Là @alexisben je masque 
- [ ] option_logo
- [ ] option_summary

2024-07-03 16:29 UTC, arnaudlevy commented on app/models/communication/block/template/person.rb
> +  has_component :option_link,         :boolean, default: true
Là @alexisben je masque  
- [ ] option_summary

2024-07-03 16:29 UTC, arnaudlevy commented on app/models/communication/block/template/post.rb
> +  has_component :option_summary,      :boolean, default: true
Là @alexisben je masque  
- [ ] option_reading_time

2024-07-03 16:29 UTC, arnaudlevy commented on app/models/communication/block/template/program.rb
> +  has_component :option_summary,      :boolean, default: false
Là @alexisben je masque tout

2024-07-03 16:29 UTC, arnaudlevy commented on app/models/communication/block/template/project.rb
> +  has_component :option_summary,      :boolean, default: false
Là @alexisben je masque tout

2024-07-04 07:59 UTC, alexisben commented on lib/tasks/app.rake
> +      template.option_summary       = template.show_description
intuitivement ça me paraît plus clean que toutes les options d'affichage d'un bloc soient au même endroit

2024-07-04 12:12 UTC, arnaudlevy commented
@Olivia206 @alexisben je crois que c'est ok

2024-07-08 08:52 UTC, alexisben commented
Niveau data, ça va bien fonctionner pour les blocs de l'extranet ? @arnaudlevy @pabois @SebouChu

2024-07-08 09:11 UTC, arnaudlevy commented
C'est à dire ?

2024-07-08 12:55 UTC, alexisben commented
On a regardé avec Sebou, les blocs extranets (partial show) doivent être mis à jour aussi dans cette PR

2024-07-08 14:25 UTC, Olivia206 commented on app/models/communication/block/template/organization.rb
> +  has_component :option_logo,         :boolean, default: true
Est-ce que c'est volontaire de mettre une distinction entre option_image et option_logo ?

2024-07-08 14:52 UTC, alexisben commented
@arnaudlevy  Pour le bloc page c'est moins compréhensible qu'avant !

Avant refonte d'options : 
![image](https://github.com/osunyorg/admin/assets/4630530/81202ec2-46bd-4204-bbe5-82a3ed105c3b)

Après refonte d'options : 
![image](https://github.com/osunyorg/admin/assets/4630530/6b87b5b5-41a2-489a-927d-6c0efab7ca98)

2024-07-12 07:45 UTC, arnaudlevy commented on app/models/communication/block/template/organization.rb
> +  has_component :option_logo,         :boolean, default: true
c'était juste de la rigueur sémantique

2024-07-12 07:46 UTC, arnaudlevy commented on app/models/communication/block/template/organization.rb
> +  has_component :option_logo,         :boolean, default: true
c'est vrai que c'est discutable, mais je crois que c'est bien, on pourrait avoir une image de l'orga qui ne serait pas le logo

2024-07-12 09:21 UTC, SebouChu approved these changes

2024-07-12 09:34 UTC, alexisben approved these changes

2024-07-12 09:34 UTC, merged