Recherche
osunyorg/admin pull request #2172
Opened 2024-08-30 08:19 UTC by arnaudlevy

2024-09-09 16:54 UTC, SebouChu requested changes

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
>          <% unless @paper.keywords.blank? %>
```suggestion
        <% unless @l10n.keywords.blank? %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
>            <p><%= @paper.keywords %></p>
```suggestion
          <p><%= @l10n.keywords %></p>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
>            <%= osuny_label Research::Journal::Paper.human_attribute_name('keywords') %>
```suggestion
          <%= osuny_label Research::Journal::Paper::Localization.human_attribute_name('keywords') %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
>          <% if @paper.authors_list.present? %>
```suggestion
        <% if @l10n.authors_list.present? %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
>            <p><%= @paper.authors_list %></p>
```suggestion
          <p><%= @l10n.authors_list %></p>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
>      <%= render 'admin/application/meta_description/show', about: @paper %>
```suggestion
    <%= render 'admin/application/meta_description/show', about: @l10n %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
> +      <% if has_content?(@paper.text)%>
```suggestion
      <% if has_content?(@l10n.text)%>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
> +        <%= osuny_label Research::Journal::Paper.human_attribute_name('text') %>
```suggestion
        <%= osuny_label Research::Journal::Paper::Localization.human_attribute_name('text') %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
> +        <%= sanitize @paper.text %>
```suggestion
        <%= sanitize @l10n.text %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
> +      <% if has_content?(@paper.bibliography)%>
```suggestion
      <% if has_content?(@l10n.bibliography) %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
> +        <%= osuny_label Research::Journal::Paper.human_attribute_name('bibliography') %>
```suggestion
        <%= osuny_label Research::Journal::Paper::Localization.human_attribute_name('bibliography') %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/show.html.erb
> +        <%= sanitize @paper.bibliography %>
```suggestion
        <%= sanitize @l10n.bibliography %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/static.html.erb
>  <% if @about.bibliography %>
```suggestion
<% if @l10n.bibliography %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/static.html.erb
>  <% if @about.bibliography %>
fix la valeur en bas

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/static.html.erb
>    <%= prepare_text_for_static @about.keywords %>
```suggestion
  <%= prepare_text_for_static @l10n.keywords %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/services/migrations/l10n/research/journal/paper/kind.rb
> +      l10n.save
```suggestion
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/_list.html.erb
> +          <% if paper.published_at.present? %>
devrait être le l10n

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/_form.html.erb
> +                      } if has_content?(paper.text) %>
```suggestion
                      } if has_content?(l10n.text) %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/_form.html.erb
> +                      } if has_content?(paper.bibliography) %>
```suggestion
                      } if has_content?(l10n.bibliography) %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/_form.html.erb
> +          <%#= f.association :people,
@arnaudlevy on en fait quoi ?

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/research/journals/papers/_form.html.erb
> +          <%= f.association :kind, collection: @journal.kinds.ordered(current_language) if @journal.kinds.any? %>
```suggestion
          <%= f.association :kind, collection: osuny_collection(@journal.kinds, localized: true) if @journal.kinds.any? %>
```

2024-09-09 16:54 UTC, SebouChu commented on app/views/admin/application/favorites/_show.html.erb
> +          title = about.respond_to?(:to_s_in) ? about.to_s_in(current_language) : about.to_s
Vérifier si tous les objets favorisables sont localizables, ce qui permettrait d'éviter ce test

2024-09-09 16:54 UTC, SebouChu commented on app/controllers/admin/research/researchers_controller.rb
>      @papers = @researcher.research_journal_papers.ordered.page(params[:page])
```suggestion
    @papers = @researcher.research_journal_papers.ordered(current_language).page(params[:page])
```

2024-09-09 16:54 UTC, SebouChu commented on app/controllers/admin/research/researchers_controller.rb
>      @papers = @researcher.research_journal_papers.ordered.page(params[:page])
```suggestion
```

2024-09-10 13:07 UTC, arnaudlevy commented on app/views/admin/research/journals/papers/_form.html.erb
> +          <%#= f.association :people,
https://github.com/osunyorg/admin/pull/2172/commits/c442215c3d9e063e8db89655317eaec2a6dae31d

2024-09-10 13:26 UTC, arnaudlevy commented on app/services/migrations/l10n/research/thesis.rb
> +
il n'y a pas de thèses

2024-09-10 15:04 UTC, arnaudlevy commented on app/views/admin/research/journals/volumes/show.html.erb
>        <%= osuny_panel Research::Journal::Paper.model_name.human(count: 2) do %>
J'ai pas compris

2024-09-10 15:09 UTC, arnaudlevy commented on app/views/admin/research/journals/papers/show.html.erb
> +      <% if has_content?(@paper.text)%>
attends @SebouChu ça devrait pas être les summary ça ?

2024-09-10 15:11 UTC, arnaudlevy commented on app/views/admin/research/journals/papers/_list.html.erb
> +          <% if paper.published_at.present? %>
pas compris

2024-09-12 08:10 UTC, pabois commented on app/views/admin/research/journals/papers/show.html.erb
> +      <% if has_content?(@paper.text)%>
on en profite pour virer les text (non utilisés sauf en demo) et les bibliography (idem).
Ces champs sont dépréciés

2024-09-12 08:12 UTC, merged