Gestion unifiée des auteurs et autrices
osunyorg/admin pull request #2352
Opened 2024-10-21 06:04 UTC by arnaudlevy

2024-10-28 14:28 UTC, SebouChu reviewed
en gros, il manque les extranets

2024-10-28 14:28 UTC, SebouChu commented on app/services/migrations/authors.rb
> +        person.update_column :is_author, person.communication_website_posts.any?
vérifier les posts d'extranet

2024-10-28 14:28 UTC, SebouChu commented on app/views/admin/communication/authors/index.html.erb
> +          <% if person.communication_website_posts.any? %>
et les extranets ?

2024-10-28 14:28 UTC, SebouChu commented on app/views/admin/communication/authors/show.html.erb
> +<% @author.author_websites.each do |website| %>
manque les extranets

2024-10-29 07:46 UTC, arnaudlevy commented on app/services/migrations/authors.rb
> +        person.update_column :is_author, person.communication_website_posts.any?
J'ai ajouté les auteurs des extranets et fait un truc beaucoup plus efficace

2024-10-31 08:54 UTC, SebouChu commented on app/views/admin/communication/authors/index.html.erb
> +              <%= Communication::Website::Post.model_name.human(count: person.communication_website_posts.size).downcase %>
```suggestion
              <%= Communication::Website::Post.model_name.human(count: person.posts.size).downcase %>
```

2024-10-31 08:56 UTC, SebouChu approved these changes

2024-10-31 08:58 UTC, SebouChu requested changes

2024-10-31 08:58 UTC, SebouChu commented on app/views/admin/communication/authors/show.html.erb
> +      <% posts = @author.communication_website_posts.where(website: website) %>
```suggestion
      <% posts = @author.communication_website_posts.where(website: website).limit(5) %>
```

2024-10-31 08:58 UTC, SebouChu commented on app/views/admin/communication/authors/show.html.erb
> +      <% posts = @author.communication_extranet_posts.where(extranet: extranet) %>
```suggestion
      <% posts = @author.communication_extranet_posts.where(extranet: extranet).limit(5) %>
```

2024-10-31 09:25 UTC, merged